server:
  port: 8084
  context-path: /gzxant/enroll

spring:
  profiles:
    active: pro
  aop:
    proxy-target-class: true
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.######
      template_exception_handler: ignore
    request-context-attribute: rc
    charset: UTF-8

  #定义图片上传的最大限制
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb

sitemesh:
  contentPath: /*
  decoratorPath: classpath:/layouts/default.jsp
  excludedPaths: /js/*,/assets/*,/css/*

management:
  security:
    enabled: false

logging.level.project.user.UserClient: DEBUG

mybatis:
  mapper-locations: classpath:mapper/sys/**/*.xml, classpath:mapper/log/**/*.xml
  type-aliases-package: com.gzxant.entity, com.gzxant.common.entity
mybatis-plus:
  mapper-locations: classpath:mapper/sys/**/*.xml, classpath:mapper/log/**/*.xml
  type-aliases-package: com.gzxant.entity, com.gzxant.common.entity
  global-config:
    id-type: 2
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
    metaObjectHandler: com.gzxant.config.plus.SysMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

security:
  basic:
    enabled: false


wechat:
  mpAppId: wx1e329c7bf0eae278
  mpAppSecret: 6af2547e8f88399cee105ec929204f3c
  mchId: 1509328281
  mchKey: smallant6AHSE858d4FUI4fZVyhUFlvC
  keyPath: \app\config\apiclient_cert.p12
  notifyUrl: http://www.zhangyingchun.cn/gzxant/enroll/api/notify
  openIdReturnUrl: http://www.zhangyingchun.cn/gzxant/enroll/front/enroll
  openIdUrl: http://www.zhangyingchun.cn/gzxant/enroll/front/wechat/userinfo
